### ISSUE TITLE
.env.supervisor missing during setup

### ISSUE THREAD

**Issue by dog-broad** [aropan/clist#332]
```
env file D:\clist\.env.supervisor not found: CreateFile D:\clist\.env.supervisor: The system cannot find the file specified.
Traceback (most recent call last):
  File "D:\clist\configure.py", line 112, in <module>
    main()
  File "D:\clist\configure.py", line 93, in main
    run_command('docker compose build dev')
  File "D:\clist\configure.py", line 84, in run_command
    subprocess.run(cmd, shell=True, check=True)
  File "C:\msys64\mingw64\lib\python3.10\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'docker compose build dev' returned non-zero exit status 1.
```

Is it alright to have an empty env file??

**Comment by aropan** [comment]
Try pulling the latest version now.
